### ISSUE TITLE
`mergeLonghand` rule from `cssnano-preset-default` remove fallback styles

### ISSUE THREAD

**Issue by grzegorzpokorski** [Timer/cssnano-simple#29]
With `mergeLonghand: true` (what cssnano-preset-default have) cssnano remove fallback CSS rules eg:

input:
```css
.foo1 {
  color: red; /* fallback */
  color: blue;
}
.foo2 {
  border-width: 10px;
  border-style: solid;
  border-color: rgba(255,0,0); /* fallback for browsers which does not support OKLCH */
  border-color: oklch(62.8%, 64.5%, 29.234%);
}
```

output:
```css
.foo1{color:red;color:blue}.foo2{border:10px solid oklch(62.8%,64.5%,29.234%)}
```

I open this issue here because I see that this plugin / package is used by next.js and I faced this problem in latest next js version (v13.1.1) and it seems there is no way to simple disable this option (i mean set `mergeLonghand` to false in nextjs).

**Comment by grzegorzpokorski** [comment]
I got around this problem by simply use CSS variables and `@supports` CSS at-rule - example below:
```css
:root{
 --custom-color: rgb(245, 255, 255);
}

@supports (color: color(display-p3 0 0 0)) {
 :root {
  --custom-color: color(display-p3 0.96859 1.00000 1.00000);
 }
}

.foo2 {
  border-color: var(--custom-color);
}
```

 By doing that I no longer need falback styles like this:
```css
.foo2 {
  border-color: rgba(255,0,0); /* fallback */
  border-color: oklch(62.8%, 64.5%, 29.234%);
}
```
so, sssnano has nothing to remove.
